-- btree_gist: the overlap constraint below needs an equality operator class
-- for tenant_id (uuid) inside a GiST index. Not generated by drizzle-kit.
CREATE EXTENSION IF NOT EXISTS btree_gist;--> statement-breakpoint
CREATE TABLE "appointments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"client_id" uuid NOT NULL,
	"starts_at" timestamp with time zone NOT NULL,
	"ends_at" timestamp with time zone NOT NULL,
	"status" text DEFAULT 'scheduled' NOT NULL,
	"location" text,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "appointments_status_known" CHECK (status in ('scheduled', 'completed', 'cancelled', 'no_show')),
	CONSTRAINT "appointments_ends_after_starts" CHECK (ends_at > starts_at)
);
--> statement-breakpoint
ALTER TABLE "appointments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "appointments" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "appointments_client_id_starts_at_idx" ON "appointments" USING btree ("client_id","starts_at");--> statement-breakpoint
CREATE INDEX "appointments_tenant_id_starts_at_idx" ON "appointments" USING btree ("tenant_id","starts_at");--> statement-breakpoint
CREATE POLICY "appointments_tenant_isolation" ON "appointments" AS PERMISSIVE FOR ALL TO "authenticated_backend" USING ("appointments"."tenant_id" = (select tenant_id from tenant_members where user_id = current_setting('app.user_id', true) limit 1)) WITH CHECK ("appointments"."tenant_id" = (select tenant_id from tenant_members where user_id = current_setting('app.user_id', true) limit 1));

--> statement-breakpoint
-- No double-booking, enforced by the database rather than by a read-then-write
-- in lib/appointments.ts. A check-then-insert has the same TOCTOU race the
-- consent grant had (two concurrent bookings both see a free slot); an
-- exclusion constraint has no window at all.
--
-- tenant_id WITH = keeps a conflict inside one tenant, so this can never
-- reveal another tenant's calendar through a constraint violation.
--
-- '[)' is half-open ON PURPOSE: an appointment ending at 10:00 and one
-- starting at 10:00 are back-to-back, not overlapping.
--
-- PARTIAL on the statuses that still occupy the slot. A cancelled or missed
-- appointment frees the time, and without the WHERE clause it would block
-- rebooking it forever. Keep this list in step with BLOCKING_STATUSES in
-- db/appointment-statuses.ts — tests/unit/appointment-overlap.test.ts fails
-- if they drift.
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_no_overlap" EXCLUDE USING gist (tenant_id WITH =, tstzrange(starts_at, ends_at, '[)') WITH &&) WHERE (status in ('scheduled', 'completed'));
